### ISSUE TITLE
Cant wear it on chest slot

### ISSUE THREAD

**Issue by shouxd** [CammiePone/Cam-s-Wearable-Backpacks#1]
Hello, I was excited to test the mod but I cant wear backpacks it in the chest slot. I know it doesnt work with trinket slots, but Im trying to use a normal slot. Does this not work when trinkets mod is detected?

**Comment by CammiePone** [comment]
Ah, okay so I probably should've explained it better on the mod page, my bad. You have to place the backpack on the ground and then shift + right click on it to wear it. Shift + right click on another block to take it off.
