### ISSUE TITLE
Trinkets compatibility reguest

### ISSUE THREAD

**Issue by sloweia** [CammiePone/Cam-s-Wearable-Backpacks#10]
I really love the mod, especially the models. But it would be cool to have Trinkets mod compatibility, it would be so balanced for vanilla expirience, but would be great for modpacks. Currently using it in my personal rpg packs, and having issues with a lot of loot. There few fabric backpacks mods that support trinkets's back slot, but they aren't nearly as good as yours.

**Comment by CammiePone** [comment]
You aren't the first person, and probably won't be the last, to ask me for the backpack to be able to go into the trinkets slot. The answer is no. I want this to be a balanced backpack mod, not one that just gives free inventory space.
