### ISSUE TITLE
[suggestion] Very small and easy enhancement

### ISSUE THREAD

**Issue by ekiplier** [CammiePone/Cam-s-Wearable-Backpacks#12]
My idea was just to remove the block-breaking particle effect for when players pick up the backpack. This made me check my inventory to make sure it was there a few times. I think making a bigger distinction between breaking and picking up the backpack would be a nice little QoL improvement to the mod :)

**Comment by CammiePone** [comment]
I'm going to be adding a button to the UI for equipping and unequipping the backpack anyways, so I don't think it's all that necessary.
