### ISSUE TITLE
Keep item in backpack when dying

### ISSUE THREAD

**Issue by domanhthang2110** [CammiePone/Cam-s-Wearable-Backpacks#13]
Just a suggestion since it's annoying to have to re-organize everything. Especially when the backpack is bigger now
Or maybe place it as a block is nice as well

**Comment by CammiePone** [comment]
Only way it's happening is if it places a block upon death, which is a nightmare of checks to make it work.

Yes, it can be done. No, I really dont want to do it. Ill leave this open though in case I change my mind

**Comment by domanhthang2110** [comment]
Huh so it's complicated. I thought it's like running whatever the code that you place it down by hand at the death position
But ty for considering it

**Comment by CammiePone** [comment]
Technically yes, but what happens if the player suffocates in sand? The backpack would be deleted then, along with all the items.

With the placing by hand, there's a lot more control over it, and I can prevent the player from placing it in a weird place. Otherwise? Not really.

**Comment by domanhthang2110** [comment]
You actually did it O.O

**Comment by CammiePone** [comment]
It's not a very great solution. It'll just place it at the nearest empty space along the y axis where the player died, and if there's none, it'll just delete whatever block is at world height.
