### ISSUE TITLE
Error trying equip backpack

### ISSUE THREAD

**Issue by kittech0** [CammiePone/Cam-s-Wearable-Backpacks#14]
When trying to equip backpack i get that error \/
[crash-2021-11-22_20.13.26-client.txt](https://github.com/CammiePone/Cammies-Wearable-Backpacks/files/7583793/crash-2021-11-22_20.13.26-client.txt)
r

**Comment by CammiePone** [comment]
That's an issue with Wildfire's Female Gender Mod, which the author knows about and is working on a fix.

**Comment by CammiePone** [comment]
Just turn off the boobs in armour setting and it'll work for now
