### ISSUE TITLE
When breaking backpack, items come out.

### ISSUE THREAD

**Issue by Targetry** [CammiePone/Cam-s-Wearable-Backpacks#16]
I really like this mod but this is the only setback.

**Comment by CammiePone** [comment]
That's intentional.

**Comment by Targetry** [comment]
Is there a way you can make it not do that?

**Comment by CammiePone** [comment]
No, because then you may as well use Inmis.

**Comment by Targetry** [comment]
Inmis unfortunately isn't updated for 1.18.

**Comment by CammiePone** [comment]
The whole point of this mod is to make backpacks that are actually balanced. Backpacks the way Mojang would add them if they were to add them into the game.

Free inventory space is not balanced.
