### ISSUE TITLE
Suggestion - Change the backpack shape

### ISSUE THREAD

**Issue by khoingt** [CammiePone/Cam-s-Wearable-Backpacks#18]
Hey, I found this backpack model that looked better :D
![image](https://user-images.githubusercontent.com/67176819/144812810-84b73cbb-82d3-4ffe-9355-dcfcf0c617d4.png)
^ the backpack model ^
here is the .json model, pls change the file extension:
[backpack.txt](https://github.com/CammiePone/Cammies-Wearable-Backpacks/files/7659226/backpack.txt)
the texture:
![back_pack](https://user-images.githubusercontent.com/67176819/144813129-ea78ece0-8975-46c8-b678-790a494f3ad1.png)

**Comment by Arathain** [comment]
did you make this model? also, the backpack being "better" or "worse" is purely subjective, in this case I'd actually say the current model works better

**Comment by CammiePone** [comment]
The model isnt going to change

**Comment by CammiePone** [comment]
I too would like to know though if you made this model. If not, where is it from?

**Comment by khoingt** [comment]
well... it's from Origin Realms, a small server

**Comment by CammiePone** [comment]
Origin Realms isn't really small, and given they don't specify a license, that means all assets are almost certainly ARR, meaning no, even if I wanted to, I couldn't add this to the mod as it would cause legal issues.
