### ISSUE TITLE
Universal Graves and Unworn Backpacks

### ISSUE THREAD

**Issue by AstoriaWinters** [CammiePone/Cam-s-Wearable-Backpacks#20]
When you die and have a backpack in your inventory it just flops out instead of going into the grave- meaning if you die to lava you then lose all your stuff. Is there a way to just have the backpack be put in the grave, please?

I am using version 2.5 of the backpacks and version 1.2.2 of the graves.

Having the backpack go into the graves would help a lot since the appeal of the graves is the protection for them as well.

Thank you.

**Comment by CammiePone** [comment]
Yknow. Maybe I should've had a check for if the backpack was on your back.

That would've been a smart thing for me to test.

**Comment by CammiePone** [comment]
Also, should mention, the backpacks by default will place themselves if they're on your back, that's why they don't go in the grave. I just never tested with one in my inventory when doing it

**Comment by CammiePone** [comment]
Anyways fix is going out now. It was just a single additional check

**Comment by AstoriaWinters** [comment]
ahh, thats fine! I figured that was the default because of other backpack mods I used did that too. I had only just found the issue when I was testing if it put the backpack out when in your inv as well and realized it poped it out (I was testing by dieing in lava lol) Thank you very much!

**Comment by CammiePone** [comment]
Np, new version is now available on both cf and modrinth

**Comment by CammiePone** [comment]
didn't mean to reopen it whoops
