### ISSUE TITLE
Incompatibility with FastBench

### ISSUE THREAD

**Issue by TropheusJ** [CammiePone/Cam-s-Wearable-Backpacks#21]
https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric

with fastbench installed, the backpack crafting grid will not visibly output any items, but clicking the slot will still craft correctly.

**Comment by CammiePone** [comment]
:pain:

**Comment by UpcraftLP** [comment]
Fastbench does not seem to be updated past Mineraft 1.18.1, which is no longer supported.
