### ISSUE TITLE
can't craft on multiplayer server.

### ISSUE THREAD

**Issue by Rocelia06** [CammiePone/Cam-s-Wearable-Backpacks#23]
Hi,

i have my own server and i want to use this mod but the mod itself does work but i can't craft the backpacks i can only get them through creative mode,

am i missing something for multiplayer server?

The rest works like it should.

When i play singleplayer i am able to craft them.

**Comment by CammiePone** [comment]
I mean, it's a regular recipe, so if it's not working then I would wager other recipes are also broken. That, or if you have something like FastWorkbench installed, it may just not be showing the output when it actually is there. Clicking the output slot may just craft the backpack anyways.

**Comment by Rocelia06** [comment]
i have tried clicking on the output slot but does not work unfortunately and i don't have fastworkbench

this is what i do have on the server right now.

![afbeelding](https://user-images.githubusercontent.com/99327891/153280798-2ace8fdd-04f6-4398-a922-9703cefb8268.png)
