### ISSUE TITLE
Config option to disable sneak+use to unequip the bag

### ISSUE THREAD

**Issue by Adirelle** [CammiePone/Cam-s-Wearable-Backpacks#24]
It is sometime undesirable to unequip the backpack by sneak-right-clicking with an empty hand. Some other mods might also use the same gesture, or you could unequip the backpack when eating one food item and sneaking in the same time.

Would it be possible to have an option to disable that feature?

**Comment by CammiePone** [comment]
I mean, yeeeaaah tho I would have to set up a config file for the mod

**Comment by xR4YM0ND** [comment]
It would be nice to set the key binds for both (unequip and equip) in options key binds ingame

**Comment by UpcraftLP** [comment]
Implemented since v2.12
