### ISSUE TITLE
Crafted items disappear

### ISSUE THREAD

**Issue by Kuggle01** [CammiePone/Cam-s-Wearable-Backpacks#29]
https://user-images.githubusercontent.com/77563171/160298150-b2efba81-cb24-4b19-96b3-a74d0e714fa9.mp4

Sometimes, when crafting items in the backpack and shift clicking them into the backpack, they just disappear, closing and re-opening the backpack will reveal the crafted item however. Not sure what exactly causes this, seems to only happen when the backpack is placed on the ground and is nearly or completely empty

**Comment by CammiePone** [comment]
I know about this one, idfk how to fix it.
