### ISSUE TITLE
Crash in 1.19.3

### ISSUE THREAD

**Issue by oDucci** [CammiePone/Cam-s-Wearable-Backpacks#37]
Game crashes whenever the mod is installed. Created a test installation with just the mod along with the Fabric API, and the issue persisted.

Log can be found [here](https://www.mediafire.com/file/lt1ku182dym7l1a/crash-2023-02-12_12.59.25-client.txt/filel).

**Comment by CammiePone** [comment]
the mod isnt updated for 1.19.3 yet. Mojang made a lot of breaking changes in that version
