### ISSUE TITLE
[1.16.5] Feature request - access via right-click

### ISSUE THREAD

**Issue by kwpugh** [CammiePone/Cam-s-Wearable-Backpacks#4]
Will you consider adding the ability to access contents via right-click in hand, in addition to placing on ground?

Regards.

**Comment by CammiePone** [comment]
nope because it can't store items when it's not on the player's back slot

**Comment by kwpugh** [comment]
aren't you just writing to NBT via the BlockEntity?

**Comment by kwpugh** [comment]
ok, I get how you got it working.  basically a chest unless you sneak right-click it onto your chest slot

**Comment by CammiePone** [comment]
yep

**Comment by CammiePone** [comment]
and it's meant to be impossible to remove from the chest slot, and if it's an item on the ground, it just spews out all its contents

**Comment by kwpugh** [comment]
ok, I was hoping I could give up on mine because yours is better looking and can place, but if you can't open in your hand, its a different use case.   Great work though!

Regards.

**Comment by kwpugh** [comment]
mine is Simple Backpacks:  https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric
