### ISSUE TITLE
Items disappeared 

### ISSUE THREAD

**Issue by Goomber364** [CammiePone/Cam-s-Wearable-Backpacks#42]
Using mod in fabric modpack "Create: Astral v2.0.4c", Minecraft version 1.18.2
When interacting with the tinker station, the backpack was accidentally unequipped. When re-equipped, all items that were previously inside bag had disappeared. As this is probably just an incompatibility issue with the Hephaestus mod (fabric version of Tinker's), I don't now if this would be able to be fixed. Attached is a short video showing the issue.

https://github.com/CammiePone/Cammies-Wearable-Backpacks/assets/133177340/925274bc-b85a-4597-bbaf-a85601bd4b6d

**Comment by CammiePone** [comment]
okay so, this is something i can fix, but i also dont keep old versions updated. i might still make a new 1.18.2 build just because i still play create astral myself, and i can fix this *kinda*. i'll see how hard it is

**Comment by Martin-Pitt** [comment]
Oof, just encountered this exact issue

**Comment by UpcraftLP** [comment]
Don't think a 1.18.2 backport is happening anymore, and it seems to already be fixed in 1.20.1.
