### ISSUE TITLE
Crash on launch with Friends&Foes on Neoforge 1.20.1

### ISSUE THREAD

**Issue by rojakmc** [CammiePone/Cam-s-Wearable-Backpacks#45]
When Friends&Foes is installed with Cammies Wearable Backpacks on Neoforge for Minecraft 1.20.1, the game with crash nearly instantly, with no crash report being generated, the game logs are below. 
https://mclo.gs/TCIKXm9

**Comment by UpcraftLP** [comment]
Fixed in v3.3.2
