### ISSUE TITLE
Backpack disappears when trying to put it on your back.

### ISSUE THREAD

**Issue by toErIpNid** [CammiePone/Cam-s-Wearable-Backpacks#5]
MC Version: 1.16.5
Fabric Version: 0.11.6
Mod Version: 1.3

Log: 
[latest.log](https://github.com/CammiePone/Cam-s-Wearable-Backpacks/files/6752022/latest.log)

Modpack Used:
[Woven-1.0.zip](https://github.com/CammiePone/Cam-s-Wearable-Backpacks/files/6752032/Woven-1.0.zip)

**Comment by CammiePone** [comment]
Somehow the block entity is null? Which shouldn't ever be happening? I'm wondering if it's a result of one of the mods in the modpack, but I'll give it some testing on its own and see what happens.

**Comment by CammiePone** [comment]
Gonna close this 'cause it'll be fixed in 1.17
