### ISSUE TITLE
Inventory is cleared after placing by hand

### ISSUE THREAD

**Issue by Felix14-v2** [CammiePone/Cam-s-Wearable-Backpacks#8]
[[Demo]](https://youtu.be/WXQiZac5Ta0)

**Technical Info**
Fabric Loader: 0.11.7
Fabric API: 0.40.8
Cammie's Wearable Backpacks: v1.5

**Comment by CammiePone** [comment]
Video's private

**Comment by CammiePone** [comment]
Uhhhh okay it's not supposed to be able to be removed from your back slot...
